-- Oracle SQL schema for Player Registration System.
-- Table naming follows a consistent lowercase_snake_case convention.
-- Entity mapping:
--   Player       -> players
--   Game         -> games
--   PlayerAndGame-> player_and_game

CREATE TABLE players (
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255),
    postal_code VARCHAR2(20),
    province VARCHAR2(50),
    phone_number VARCHAR2(30),
    CONSTRAINT pk_players PRIMARY KEY (player_id)
);

CREATE TABLE games (
    game_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    game_title VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (game_id),
    CONSTRAINT uk_games_title UNIQUE (game_title)
);

CREATE TABLE player_and_game (
    player_game_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    player_id NUMBER NOT NULL,
    game_id NUMBER NOT NULL,
    playing_date DATE NOT NULL,
    score NUMBER(6,0) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_player_and_game PRIMARY KEY (player_game_id),
    CONSTRAINT fk_pag_player
        FOREIGN KEY (player_id)
        REFERENCES players (player_id),
    CONSTRAINT fk_pag_game
        FOREIGN KEY (game_id)
        REFERENCES games (game_id),
    CONSTRAINT chk_pag_score_non_negative CHECK (score >= 0),
    CONSTRAINT uk_pag_player_game_date UNIQUE (player_id, game_id, playing_date)
);