-- Oracle SQL schema baseline for the player registration system.
-- Adjust lengths and constraints as required by the application code.

CREATE TABLE players (
    player_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255),
    postal_code VARCHAR2(20),
    province VARCHAR2(50),
    phone_number VARCHAR2(30)
);

CREATE TABLE games (
    game_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_title VARCHAR2(150) NOT NULL
);

CREATE TABLE player_and_game (
    player_game_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id NUMBER NOT NULL,
    game_id NUMBER NOT NULL,
    playing_date DATE,
    score NUMBER,
    CONSTRAINT fk_pag_player
        FOREIGN KEY (player_id)
        REFERENCES players (player_id),
    CONSTRAINT fk_pag_game
        FOREIGN KEY (game_id)
        REFERENCES games (game_id)
);